### ISSUE TITLE
term disappeared? hancestro:0308 "has country of origin"

### ISSUE THREAD

**Issue by ddooley** [EBISPOT/ancestro#11]
I believe this was a term and id in ancestro, but has it been discontinued in hancestro?
I'll fashion a FoodOn id for it if necessary.

**Comment by daniwelter** [comment]
Hmm, the term is definitely still in the source ontology. I will investigate what happened.

**Comment by daniwelter** [comment]
@ddooley Are you referring to the version of the ontology that's shown in OLS? If so, there's definitely something not quite right with it. If you look at the source ontology in the OBO foundry or on Github though, the term is still available.

**Comment by ddooley** [comment]
Indeed I was checking OLS.  Apparently OLS had some ontology synchronization issues but not sure this has anything to do with that.  Perhaps you could raise the missing term issue with them?

**Comment by daniwelter** [comment]
I have created a new release of HANCESTRO today and will check on the missing term issue in a couple of days, once the new version has been picked up by OLS.

**Comment by daniwelter** [comment]
@ddooley The term is still missing in OLS (but definitely in the ontology) so I've raised the matter again with the OLS team. I expect there will be a bit more movement on HANCESTRO in the next couple of months as it is now used by a number of other projects, so don't hesitate to flag issues or request new terms.

**Comment by daniwelter** [comment]
We now know the source of the issue, which is due to a hiccup in the ROBOT command used for generating the (default) inferred version of the ontology. Another release is planned for the first week of December, at which point this will definitely be fixed.

**Comment by ddooley** [comment]
Ok, good to know, thanks!

**Comment by daniwelter** [comment]
@ddooley The term is now visible again in OLS. Apologies it took so long to resolve this.

**Comment by daniwelter** [comment]
@ddooley I could be wrong but I think the OBO PURL resolver is case sensitive. http://purl.obolibrary.org/obo/HANCESTRO_0308 resolves fine for me.

**Comment by daniwelter** [comment]
Yes, I just double-checked v1.0 and property labels have always been single-word camel case. The only major change in terms of casing between v1 and v2 is the upper case purls and the rename from ANCESTRO to HANCESTRO as per request of the OBO foundry

**Comment by ddooley** [comment]
Ok, thanks! My bad!
