### ISSUE TITLE
Add documentation describing why to use hANCESTRO vs NCIT

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/ancestro#12]
It seems hANCESTRO overlaps a lot with the branch of another ontology in OBO, NCIT: 

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C17049

![image](https://user-images.githubusercontent.com/50745/86038807-5c4f0f80-b9f6-11ea-98da-a83fe4c82eb2.png)

[aside: I think the name of the root class in NCIT is problematic, see https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/60]

I think we should at least have mappings between the two (I can help with this).

But I think it would be useful to have more background documentation on the hancestro page: http://obofoundry.org/ontology/hancestro - what are the relevant advantages of one over the other? Is hANCESTOR only intended for GWAS? Why?

This might help other communities trying to find a vocabulary to use for concepts such as ethnicity: https://github.com/GenomicsStandardsConsortium/mixs/issues/59

It looks like the 2018 paper does not mention 
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1396-2

**Comment by cmungall** [comment]
There is also ethnic group in NCIT: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16564

**Comment by daniwelter** [comment]
Documentation now available in new [FAQ section](https://github.com/EBISPOT/ancestro/blob/master/faq.md)
