### ISSUE TITLE
unusual categorization: American is-a European

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/ancestro#13]
https://www.ebi.ac.uk/ols/ontologies/hancestro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHANCESTRO_0463&viewMode=All&siblings=false

![image](https://user-images.githubusercontent.com/50745/86044445-f31fca00-b9fe-11ea-93d8-aa0d2513852a.png)

I get why you would add something like this, but I think you need to at least provide a bit more context for people, provide some kind of definition of what you mean by American and European, consider using different labels, and provide some high level documentation on your approach to categorization

**Comment by daniwelter** [comment]
Agreed, this looks odd. I could have sworn "American" was classed as an uncategorised population. I will check with the GWAS team and either move or clarify.

**Comment by daniwelter** [comment]
This issue has been addressed in today's release of HANCESTRO.
