### ISSUE TITLE
NTRs for Esan, Luhya, Maasai, Mende ethnic groups

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/ancestro#14]
Hello, we would like to request new terms for 4 of the ethnic groups currently not in HANCESTRO. These are ethnic groups that were sampled in the 1000 Genomes Project. 

- Esan
- Luhya
- Maasai
- Mende

They would all be a subclass of Sub-Saharan African (http://purl.obolibrary.org/obo/HANCESTRO_0011).

**Comment by daniwelter** [comment]
@bonitalam We'd be happy to add these ancestral groups. Could you please provide definitions?

**Comment by bonitalam** [comment]
Great, thank you @daniwelter! Here are some definitions

**Esan:** The Esan people are one of the major ethnic groups in Edo State, Nigeria who speak the Esan language. (PMID:10146569)

**Luhya:** The Luhya are the second-largest ethnic group in Kenya and are comprised of subgroups that speak a common Bantu language. (PMID: 27813082)

**Maasai:** The Maasai are an indigenous African ethnic group of semi-nomadic people located in northern Tanzania and Kenya. (PMID:29868928) 

**Mende:** The Mende people are one of the largest ethnic groups in Sierra Leone who speak a language of the Mande branch of the Niger-Congo family. (PMID:15761855)

**Comment by daniwelter** [comment]
@bonitalam Based on the definitions you provide, these sound like cultural ethnic groups rather than genetic populations. Would you be able to include a reference to the genetic population groups as well, please?

**Comment by bonitalam** [comment]
Sure, let me know if these would suffice:

- [PMID:28049708](https://pubmed.ncbi.nlm.nih.gov/28049708/): Investigation of phased genomes/haplotypes from three of the populations - Esan, Maasai, and Mende 
- [PMID:22373165](https://pubmed.ncbi.nlm.nih.gov/22373165/): Rare variant density study of Luhya population (vs. six other populations studied in the 1000 Genomes Project) 
- [PMID:26673965](https://pubmed.ncbi.nlm.nih.gov/26673965/): Study of the FcγR variants in various African (including Luhya) and Caucasian individuals

**Comment by daniwelter** [comment]
@bonitalam The terms you requested have been created and are included in today's release of HANCESTRO (v2.4). They should propagate to all the usual channels in the coming days. Apologies for the delay in getting this completed.

Could you please let me know which project you intend to use these terms for? I'd like to update the documentation with usage examples.

**Comment by bonitalam** [comment]
No problem, thank you for creating these terms @daniwelter! 

We are planning on switching to HANCESTRO to annotate the donors we have for the [ENCODE](https://www.encodeproject.org/) project.

I also have another question, and I wasn't sure it was worth opening another issue for so I'll just ask it here. We were wondering how HANCESTRO would advise on annotating multi-ethnic donors? Currently, we just annotate using one term/identifier, and I think it makes sense to change to an array where multiple terms could be used. I assume it would be be difficult to manage making new terms for every potential ethnic combination as needed.

**Comment by daniwelter** [comment]
@bonitalam That's a really good question. Multi-faceted annotations are always tricky. If your primary goal is to capture the reported information as closely as possible, I would go down the array/multi-term annotation route. It is however worth remembering that individuals from a complex multi-ethnic background technically no longer fit the definition of each of their individual ancestral groups but rather represent a novel admixture of the component groups. Some admixed ancestral groups, such as Hispanic-Latin American are well-described but I don't think it would be possible or practical to explicitly describe every possible combination of admixture.
As an alternative solution, we created the term `admixed ancestry` (HANCESTRO:0306) for exactly this purpose. You could include this in lists of terms for multi-ethnic individuals to really highlight that reason behind the multi-term annotation. Would this suit your use case?

**Comment by bonitalam** [comment]
Thank you for the input @daniwelter and pointing to that "admixed ancestry" term! I definitely think your suggested approach of using a multi-term annotation route and designating "admixed ancestry" would work for our use case and makes the most sense. I greatly appreciate all your help.
