### ISSUE TITLE
Request for more general Arab term

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/ancestro#15]
Hello, I am working on using HANCESTRO instead of SNOMED to annotate the ethnicity of donors and mapping our current terms to HANCESTRO. Currently we have donors that are identified as having Arab ethnicity. 

There seems to be two terms that exist in HANCESTRO that are more specific than what we can use.

- Arab Israeli founder: http://purl.obolibrary.org/obo/HANCESTRO_0555
- Saudi: http://purl.obolibrary.org/obo/HANCESTRO_0449

Would it be possible to have a more general Arab term and have Arab Israeli founder and Saudi be subclasses of it?

## Preferred term label

Arab

## Textual definition

Includes individuals with ethnic origins in the Semitic people populating the Arabian Peninsula and other countries in the Middle East and Northern Africa.   [PMID:27393651](https://pubmed.ncbi.nlm.nih.gov/27393651/), [PMID:28106113](https://pubmed.ncbi.nlm.nih.gov/28106113/)

## Suggested parent term

Greater Middle Eastern (Middle Eastern, North African or Persian): http://purl.obolibrary.org/obo/HANCESTRO_0015

**Comment by daniwelter** [comment]
I would be happy to create the term as requested but I can't commit to moving the existing two terms under it without further research.

**Comment by bonitalam** [comment]
Thank you @daniwelter, the term as requested works for us! I will definitely share any publications that might help shed some light on if subclassing the other terms would be appropriate or not. I think I only have one more request for another term for now. I will definitely submit that by the end of this month.

**Comment by daniwelter** [comment]
Term now available
