### ISSUE TITLE
NTR: Eskimo

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/ancestro#16]
Hello, the ENCODE project has a request for an Eskimo term to be made. Thank you for all your help! 

## Preferred term label

Eskimo

## Textual definition

Native people residing in the Arctic of Alaska, northern Canada, Greenland, or eastern Siberia [PMID:25884279](https://pubmed.ncbi.nlm.nih.gov/25884279/), [PMID:29220501](https://pubmed.ncbi.nlm.nih.gov/29220501/)

## Suggested parent term

uncategorised population (HANCESTRO:0018) - doesn't seem like this term would fit under any of the defined ancestry categories

**Comment by daniwelter** [comment]
Term now available
