### ISSUE TITLE
Revise hierarchy: Martu Australian Aboriginal

### ISSUE THREAD

**Issue by peupeubangbang** [EBISPOT/ancestro#25]
**HANCESTRO term**
Martu Australian Aboriginal HANCESTRO:0587
**Suggested revision and reasons**
Place under parent Australian Aboriginal HANCESTRO:0552 once class is revised and new term available per #23  and #24 

**Add synonym**
Martu Aboriginal Australian, Mardu Australian Aboriginal, Mardu Aboriginal Australian

**Add textual definition**
The Martu Australian Aboriginal people are from the Western Desert region located across the Pilbara in Western Australia

**Comment by daniwelter** [comment]
@peupeubangbang Could you please provide a reference that supports the re-categorisation of Martu Australian Aboriginal from uncategorised to Australian Aboriginal?

**Comment by peupeubangbang** [comment]
@daniwelter here we are 😃 PMID:27070114

**Comment by daniwelter** [comment]
Definition, synonyms and reference added. Term reclassified under Aboriginal Australian HANCESTRO:0552.
