### ISSUE TITLE
Requesting new terms: Singaporean Malay and Singaporean Indian

### ISSUE THREAD

**Issue by khkianhong** [EBISPOT/ancestro#26]
Hello,

I'd like to request two new HANCESTRO terms: Singaporean Malay and Singaporean Indian. Thank you for your help.
<br><br>

label (name) of the new term: 
**Singaporean Malay**

definition: 
**Includes individuals who either self-report or have been described by authors as Singaporean Malay. PMIDs: 19700652, 31626772.**

for new ancestry groups, please provide links to at least 2 scientific publications referencing and describing the ancestry group in question: 
**https://pubmed.ncbi.nlm.nih.gov/19700652/, https://pubmed.ncbi.nlm.nih.gov/31626772/**

the preferred parent term: 
**"ancestry category/Asian/South East Asian/"**

<br><br>

label (name) of the new term: 
**Singaporean Indian**

definition: 
**Includes individuals who either self-report or have been described by authors as Singaporean Indian. PMIDs: 19700652, 31626772.**

for new ancestry groups, please provide links to at least 2 scientific publications referencing and describing the ancestry group in question: 
**https://pubmed.ncbi.nlm.nih.gov/19700652/, https://pubmed.ncbi.nlm.nih.gov/31626772/**

the preferred parent term: 
**"ancestry category/Asian/South Asian/Indian/"**

**Comment by daniwelter** [comment]
New terms added as requested. IDs will be HANCESTRO:0597 (Singaporean Malay) and HANCESTRO:0598 (Singaporean Indian)
