### ISSUE TITLE
Update on transition to OBOFoundry

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [EBISPOT/ancestro#7]
I'm curious about how OBOFoundry entry & id issue is coming along? Ancestro import PURLS were raised over on FoodOn at https://github.com/FoodOntology/foodon/issues/26# .  Thanks,

Damion

**Comment by daniwelter** [comment]
Hi Damion,
I intend for the next release of ancestro to happen by the end of June. Ancestro identifiers will change from ancestro to hancestro to reflect the human-specific context.
Thanks
Dani

**Comment by Public-Health-Bioinformatics** [comment]
Ok. I'm curious - are you going to adopt GAZ ontology identifiers for country, or use some other geo ontology/URI identifiers?

**Comment by daniwelter** [comment]
Hi Damion, sorry it took so long but ancestro v2 aka hancestro is now out(ish). I haven't actually resolved the country identifiers issue yet but current thinking is to provide xrefs to other identifiers and/or use geo URIs.

**Comment by Public-Health-Bioinformatics** [comment]
Ok. Could you let me know when it is registered in OBOFoundry? At moment I'm getting some flack about unresolvable URLS like http://purl.obolibrary.org/obo/HANCESTRO_0035 .  

Also, I would now strongly advocate for using GAZ ontology identifiers for country/region in the new hancestry since OLS and Ontobee provide that natively.  I can provide the ancestro-gaz mapping that I manually curated if it helps. They enable the "[demonym] isDemonym of [Gazetteer country/region]" e.g. https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http://purl.obolibrary.org/obo/ancestro_0363. The reason I say this is reuse of your ontology would otherwise be encumbered by the "custom" list of country/region identifiers that would require SPARQL contortions to resolve in each adopting system. 

GAZ is getting some more curation attention according to Lynn Shriml.  This would provide a full OBOFoundry context that would then be a platform to map out to the rest of the world as needed.  GeoNames is indeed a great contender but it has no BFO context. I'd like to see GAZ xref to GeoNames via hasDbXref, as the conversion in/out of the OBOFoundry community as a whole. Perhaps we can talk Lynn into a mini-project on that subject, then you wouldn't have to curate that info within hancestro.

**Comment by daniwelter** [comment]
OBO foundry registration is now complete. Mappings to GAZ identifiers should be addressed in another ticket.
